export const artsAndCrafts = [
  '3D Modeling',
  '3D Art',
  'Acting',
  'Architecture',
  'Art Walks and Tours',
  'Artist',
  'Antique Collecting',
  'Beadwork',
  'Card Making',
  'Cigar',
  'Costume Making',
  'Coupon Clipping',
  'Crafts',
  'Crocheting',
  'Digital Art',
  'Drama',
  'Drawing',
  'DIY',
  'Digital Scrapbooking',
  'Figure Drawing',
  'Fine Art',
  'Fiber Art',
  'Fabric Crafts',
  'Home Decorating',
  'Group Art',
  'Historic Buildings',
  'Illustration',
  'Interior Decorating',
  'Improv',
  'Industrial Design',
  'Jewelry Making',
  'Life Drawing',
  'Knitting',
  'Mixed Media Art',
  'Museum',
  'Musical',
  'Needlework',
  'Open Mic',
  'Origami',
  'Painting',
  'Performing Art',
  'Paper Crafts',
  'Quilting',
  'Rubber Stamping',
  'Scrapbook Crops',
  'Scrapbooking',
  'Sewing',
  'Stampin Up!',
  'Sketching',
  'Spoken Word',
  'Storytelling',
  'Theater',
  'Visual Art',
  'Voice Acting',
  'Yarn',
];

export const animes = [
  'Demon Slayer',
  'Cowboy Bebop',
  'Jujutsu Kaisen',
  'Fullmetal Alchemist',
  'Attack on Titan',
  'Naruto',
  'Death Note',
  "Jojo's Bizarre Adventure",
  'Steins;Gate',
  'Bleach',
  'Castlevania',
  'One Punch Man',
  'Avatar the Last Airbender',
  'My Hero Academia',
  'Cyberpunk',
  'One piece',
  'Dragon Ball',
  'Hunter x Hunter',
  'Rurouni Kenshin',
  'Trigun',
  'Yu Yu Hakusho',
  'Yugioh',
  'Neon Genesis Evangelion',
  'Code Geass',
  'Hajime no Ippo',
  'Gintama',
  'Blue Lock',
  'Banana Fish',
];

export const apps = [
  'Adobe Creative Cloud',
  'Adobe Illustrator',
  'Adobe Indesign',
  'Adobe Photoshop',
  'Airbnb',
  'Behance',
  'ChatGPT',
  'Discord',
  'Dribbble',
  'ebay',
  'Facebook',
  'Figma',
  'Github',
  'Gitlab',
  'Instagram',
  'Khan Academy',
  'Leetcode',
  'LinkedIn',
  'Medium',
  'Meetup',
  'Netflix',
  'Notion',
  'Opensea',
  'Patreon',
  'Paypal',
  'Picsart',
  'Pinterest',
  'Podcast',
  'Product Hunt',
  'Quora',
  'Reddit',
  'Slack',
  'Snapchat',
  'Spotify',
  'Stackoverflow',
  'Tiktok',
  'Twitch',
  'Twitter',
  'Uber Eats',
  'Udemy',
  'Waze',
  'Wordpress',
  'Yelp',
  'Youtube',
  'Zenly',
  'Zoom',
];

export const books = ['Book Club', 'Book Swap', 'Classic Books', 'Fiction', 'Literature', 'Novel Reading', 'Reading'];

export const business = [
  'Accounting',
  'Advertising',
  'Affiliate',
  'Investing',
  'Networking',
  'Online Business',
  'Business Owner',
  'Brainstorming',
  'Marketing',
  'Career Coaching',
  'Cashflow',
  'Conference',
  'Courage',
  'Real Estate',
  'Commodities Trade',
  'Communication',
  'export construction',
  'Consulting',
  'Coworking',
  'Currency Trading',
  'Creative',
  'Day Traders',
  'Design Thinking',
  'Digital Marketing',
  'Direct Sales',
  'E-Business Owner',
  'Economics',
  'Entrepreneurship',
  'Event Planning',
  'Coaching',
  'Finance',
  'Financial Planning',
  'Forex Trading',
  'Freelance',
  'Fundraising',
  'Futures Trading',
  'Flexibility',
  'Google adWords',
  'Healthcare Innovation',
  'Home Buyer',
  'Human Resources',
  'Impromptu Speaking',
  'Interior Design',
  'Integrity',
  'Job Interview Prep',
  'Job Search',
  'Landlords',
  'Lawyer',
  'Lead Generation',
  'Leadership',
  'MasterMinds',
  'Media',
  'Mentoring',
  'Millionaire',
  'Mompreneurs',
  'Money',
  'Mortgage Professionals',
  'Networking Leads',
  'Networking for Job Seekers',
  'New Career',
  'Online Marketing',
  'Online News Association',
  'Options Trading',
  'Pay Per Click',
  'Personal Finance',
  'Planning',
  'Presentations',
  'Productivity',
  'Project Management',
  'Psychotherapists',
  'Public Relations',
  'Public Speaking',
  'Quickbooks',
  'Radio Broadcasting & Production',
  'Real Estate',
  'Reporters and Journalists',
  'Retirement Planning',
  'Reliability',
  'RelationshipBuilding',
  'Sales',
  'Sales Training',
  'Saving Money',
  'Selling',
  'Sharing economy',
  'Small Business',
  'Social Commerce',
  'Startup',
  'Stategic HR',
  'Stock Investing',
  'Stock Trading',
  'Swing Traders',
  'Team Building',
  'Team Management',
  'Time Management',
  'Technical Analysis',
  'Toastmaster',
  'Trading',
  'Unemployment Support',
  'Venture Capital',
  'Wealth Building',
  'Wedding Planning',
  'Entrepreneur',
  'Work At Home',
  'Work-Life Balance',
  'Working Abroad',
  'eBay Seller',
];

export const finance = [];

export const vehicles = [
  'Auto Racing',
  'Automotive',
  'Car',
  'Cruiser Bike',
  'Ducati',
  'Biker',
  'Formula 1',
  'Four Wheeler',
  'Harley-Davidson',
  'Honda',
  'Jeep',
  'Kawasaki',
  'Motorcycle',
  'Motorcycle Touring',
  'Off-Road Vehicle',
  'Scooter',
  'Sport Bike',
  'Sports Car',
  'Suzuki',
  'Yamaha',
];

export const dancing = [
  'Argentine Tango',
  'Bachata',
  'Ballet',
  'Belly Dance',
  'Bollywood Dancing',
  'Burlesque',
  'Cabaret',
  'Conscious Movement',
  'Country Dancing',
  'Dance Lessons',
  'Ecstatic Dance',
  'Fire Performer',
  'Flamenco',
  'Hooping',
  'Latin Dance',
  'Line Dancing',
  'Poi',
  'Salsa Dance',
  'Samba',
  'Social Dancing',
  'Steppers',
  'Swing Dancing',
  'Trance Dance',
];

export const education = [
  'History',
  'Astronomy',
  'Biology',
  'Cognitive Science',
  'College Student',
  'Communication Skill',
  'Workshop',
  'Critical Thinking',
  'Debate',
  'Engineering',
  'Ethics',
  'Evolution',
  'Getting Organized',
  'Graduate Students',
  'Homeschool Support',
  'Intellectual Discussion',
  'Knowledge Sharing',
  'Life Sciences',
  'Myers-Briggs Type Indicator',
  'Natural Learning',
  'Neuroscience',
  'Philosophy',
  'Physics',
  'Psychology',
  'Quantum Physics',
  'Rhetorik',
  'Science',
  'Sexual Education',
  'Socrates Cafe',
  'Space Exploration',
  'Teacher',
  'Vocal',
];

export const fashionAndBeauty = [
  'Beauty',
  'Brides-to-be',
  'Bargain Shopping',
  'Curly Hair',
  'Fashion Design',
  'Frugal Shopping',
  'Hair Styling',
  'Happy to be Nappy',
  'Kinky Hair',
  'Makeovers',
  'Makeup',
  'Makeup Artists',
  'Natural Hair',
  'Safe Skin Care & Cosmetics',
  'Shopping',
  'Skin Care',
  'Steampunk',
  'Thrift Shoppers',
  'Weddings',
];

export const fitnessAndHealth = [
  'Aerobics',
  'BeachBody',
  'Beachbody Workouts',
  'Bootcamps',
  'Boxing',
  'Core Fitness',
  'CrossFit',
  'Cycling for Fitness',
  'Dance Fitness',
  'Endurance Athletes',
  'Exercise',
  'Fat Loss Workout',
  'Fitness',
  'Fitness Boot Camp',
  'Group Fitness Training',
  'Kettlebell',
  'Kickboxing',
  'Leisure Walking',
  'Marathon',
  'Parkour',
  'Personal Training',
  'Pilates',
  'Pole Dancing',
  'Roller Skating',
  'Running',
  'Spinning',
  'Swimming',
  'Triathlon',
  'Walking',
  'Weight Loss',
  'Weight Loss Support',
  'Workout',
  'Zumba',
  'Abundance And Prosperity',
  'Achieving Goals',
  'Acupuncture',
  'Alternative Medicine',
  'Anger Management',
  'Anti-Aging',
  'Aromatherapy',
  'Art Therapy',
  'Autistic Spectrum Disorders',
  'Ayurveda',
  'Bhakti Yoga',
  'Breathing Meditation',
  'Breathwork',
  'Buddhist Meditation',
  'Cancer and Nutrition',
  'Chinese Medicine',
  'Chiropractic Health',
  'Conscious Living',
  'Detoxification',
  'Diabetes',
  'Diet',
  'EFT (Emotional Freedom Technique)',
  'Emotional Healing',
  'Essential Oils',
  'Gentle Yoga',
  'Goal Setting & Accountability',
  'Guided Meditation',
  'Hatha Yoga',
  'Healing Through Movement',
  'Health Freedom',
  'Healthy Family and Healthy Environment',
  'Healthy Living',
  'Herbalism',
  'Herbalists',
  'Holistic Health',
  'Human Sexuality',
  'Hypnotherapy',
  'Intimacy',
  'Kirtan',
  'Life Coaching',
  'Massage',
  'Medical Marijuana',
  'Meditation',
  'Mind Body Wellness',
  'Mindfulness',
  'Natural Health',
  'Nutrition',
  'Personal Achievement',
  'Pranic Healing',
  'Professional Counseling',
  'Psychotherapy',
  'Qi Gong',
  'Relationship Building',
  'Relaxation',
  'Self-Awareness',
  'Shyness',
  'Spa',
  'Stress Management',
  'Tai Chi',
  'Theta Healing',
  'Vitamins',
  'Wellness',
  'Yoga',
];

export const foodsAndDrinks = [
  'Afternoon Tea',
  'Asian Food',
  'BBQ',
  'Baking',
  'Beer',
  'Breakfast',
  'Brunch',
  'Caveman Diet',
  'Chocolate',
  'Cocktails',
  'Coffee',
  'Cooking',
  'Dessert',
  'Dinner',
  'Drinking',
  'Ethnic Food',
  'Exploring New Restaurants',
  'Fine Dining',
  'Foodie',
  'Foraging',
  'French Food',
  'Gluten-Free',
  'Gourmet Cooking',
  'High Tea',
  'Homebrewing',
  'International Cuisine',
  'Italian Food',
  'Living Foods',
  'Local Food',
  'Martini',
  'Organic Foods',
  'Paleo Diet',
  'Plant-Based Nutrition',
  'Potluck',
  'Primal Blueprint',
  'Raw Food',
  'Raw Potlucks',
  'Raw Vegan',
  'Restaurant',
  'Sake',
  'Slow Food',
  'Sushi',
  'Sustainable Food',
  'Tea',
  'Vegan',
  'Vegetarian',
  'Wine',
];

export const gamings = [
  'Amtgard',
  'Backgammon',
  'Billiard',
  'Board Game',
  'Bridge',
  'Bunco',
  'Card Game',
  'Casino Game',
  'Chess',
  'Console Gaming',
  'Cribbage',
  'D20 Gaming',
  'Dice Game',
  'Dungeons & Dragons',
  'Euchre',
  'Euro Game',
  'Game Night',
  'Gaming',
  'Go',
  'Live Action Role Playing',
  'MMORPG',
  'Magic The Gathering',
  'Mah Jong',
  'Pathfinder Roleplaying Game',
  'Poker',
  'Pool',
  'Scrabble',
  'Settlers of Catan',
  'Skeeball',
  'Spades',
  'Strategy Board Games',
  'Strategy Games',
  'Sword Fighting',
  'Tabletop Role Playing and Board Games',
  "Texas Hold 'em",
  'Trivia',
  'White Wolf',
  'Word Gaming',
  'World of Darkness',
];

export const languagesAndEthnic = [
  'African Americans',
  'African Culture',
  'Africans',
  'American Sign Language',
  'Arabic Culture',
  'Arabic Language',
  'Asian Americans',
  'Asians',
  'Australian Culture',
  'Bhangra',
  'Bilingual Spanish/English',
  'Black Expressions',
  'Black Identity',
  'Black Men',
  'Black Women',
  'Blackology',
  'Brazilian Culture',
  'British',
  'British Culture',
  'Cantonese Language',
  'Caribbean Culture',
  'Celtic Culture',
  'Chinese Culture',
  'Chinese language',
  'Cultural Diversity',
  'Culture',
  'Culture Exchange',
  'Danish Language',
  'Desi Culture',
  'Desis',
  'Deutsch',
  'Dutch Language',
  'ESL practice',
  'English Language',
  'English as a Second Language',
  'Español',
  'European Culture',
  'Expat',
  'Expat American',
  'Expat Australian',
  'Expat Brazilian',
  'Expat British',
  'Expat Canadian',
  'Expat Caribbean',
  'Expat Chinese',
  'Expat European',
  'Expat French',
  'Expat German',
  'Expat Indian',
  'Expat Irish',
  'Expat Italian',
  'Expat Japanese',
  'Expat Russian',
  'Expat Spanish',
  'Expat Swiss',
  'Francophone Culture',
  'French Culture',
  'French Language',
  'French Students',
  'German Conversation',
  'German Culture',
  'German Language',
  'Greek Culture',
  'Hebrew Language',
  'Hindi Language',
  'Hong Kong Culture',
  'Hungarian Language',
  'Indian Culture',
  'Indian Food',
  'International Friends',
  'International and Exchange Students',
  'Irish Culture',
  'Italian Culture',
  'Italian Language',
  'Italiano',
  'Japanese Culture',
  'Japanese Food',
  'Japanese Language',
  'Korean Culture',
  'Korean Language',
  'Language Exchange',
  'Latinas',
  'Latino Culture',
  'Mandarin Language',
  'Middle Eastern Culture',
  'Multicultural',
  'Multiracial',
  'Native Americans',
  'Pakistanis',
  'Polish Language',
  'Portuguese Language',
  'Russian Culture',
  'Russian Language',
  'Russians',
  'South Asians',
  'Spanish & English Language Exchange',
  'Spanish Culture',
  'Spanish Language',
  'Taiwanese Culture',
  'Taiwanese Language',
  'Vietnamese Culture',
  'Vietnamese Language',
];

export const films = [
  'Animation',
  'Arthouse',
  'B-Movies',
  'Bollywood Films',
  'British Comedies',
  'Classic Films',
  'Cult Films',
  'Digital Video',
  'Documentary Films',
  'Film',
  'Filmmaking',
  'Foreign Films',
  'Horror Films',
  'Independent Filmmaking',
  'Indie Film',
  'Japanese Film',
  'Movie Nights',
  'Video Editing',
  'Videography',
];

export const music = [
  "80's Music",
  'A Cappella',
  'Acoustic Guitar',
  'Acoustic Jams',
  'Acoustic Music',
  'African Drumming',
  'African Music',
  'Bluegrass',
  'Blues',
  'Chamber Music',
  'Choir',
  'Classical Music',
  'Concerts',
  'Drum Circle',
  'Drums',
  'Electronic Dance Music',
  'Electronic Music',
  'Folk Music',
  'Group Singing',
  'Guitar',
  'Hand Drumming',
  'Heavy Metal',
  'Hip Hop',
  'House Music',
  'Indian Music',
  'Indie',
  'Indie Music',
  'Jam Band',
  'Jam Sessions',
  'Japanese Pop',
  'Jazz',
  'Jazz Musicians',
  'Jazz Singers',
  'Karaoke',
  'Latin Music',
  'Live Jazz Music',
  'Live Music',
  'Middle Eastern Music',
  'Music',
  'Music Industry',
  'Music Production',
  'Musicians',
  'Opera',
  'Pipes and Drums',
  'Reggae',
  'Rock Music',
  'Singing',
  'Songwriting',
  'Soul Music',
  'Symphony',
  'Trance Music',
  'Ukulele',
  'Vocal Training',
];

export const spirituality = [
  'A Course In Miracles',
  'Abraham Hicks',
  'Adult Indigo',
  'Advaita Vedanta',
  'Angels',
  'Anthony Robbins',
  'Ascension',
  'Astral Projection',
  'Astrology',
  'Authenticity',
  'Awakening',
  'Awareness',
  'Bnei Baruch Kabbalah',
  'Byron Katie',
  'Carl Jung',
  'Centers for Spiritual Living',
  'Chakra Clearing',
  'Chakras',
  'Channeling',
  'Chanting',
  'Christian Mysticism',
  'Consciousness',
  'Crystal Healing',
  'Crystals and Stones',
  'Distant Healing',
  'Divine Guidance',
  'Dreams',
  'Druid',
  'Earth Healing',
  'Earth-Based Spirituality',
  'Eckankar',
  'Eckhart Tolle',
  'Energy Healing',
  'Enlightenment',
  'Evolution of Consciousness',
  'Evolutionary Consciousness',
  'Feng Shui',
  'G.I. Gurdjieff',
  'Gnostic',
  'Goddess',
  'Healing Arts',
  'Healing Circle',
  'Higher Consciousness',
  'Hypnosis',
  'I Am Happy Project',
  'Indigo Children',
  'Inner Goddess',
  'Inner Wisdom',
  'Inner peace',
  'Inspirational',
  'Integral Spirituality',
  'Intuition',
  'Kabbalah',
  'Ken Wilber',
  'Law of Attraction',
  'Law of Attraction & Positive Thinking',
  'Lightworkers',
  'Lucid Dreaming',
  'Magick',
  'Manifestation',
  'Meaning of Life',
  'Mediumship',
  'Metaphysics',
  'Mind Body Connection',
  'Mysticism',
  'Mythology',
  'NLP (Neuro-Linguistic Programming)',
  'NLP Coaching',
  'Native American Spirituality',
  'New Age Spirituality',
  'New Thought',
  'Nondualism',
  'Occult',
  'Oneness',
  'Oneness Blessing',
  'Osho',
  'Pagan Fellowship',
  'Past Life Regression',
  'Past Lives',
  'Positive Thinking',
  'Prayer Meditation and Contemplation',
  'Psychics',
  'Purposeful Living',
  'Quantum-Touch Healing',
  'Reiki',
  'Reiki Classes',
  'Reiki Share',
  'Reincarnation',
  'Retreats',
  'Sacred Ceremony and Ritual',
  'Sacred Feminine',
  'Sacred Sexuality',
  'Satsang',
  'Science of Mind',
  'Self',
  'Self Exploration',
  'Self-Realization',
  'Sensuality',
  'Shamanic Drumming',
  'Shamanic Healing',
  'Shamanic Journeying',
  'Shamanism',
  'Soul Healing',
  'Soul Travel',
  'Sound Healing',
  'Sound Vibrational Healing',
  'Spiritual Awakening',
  'Spiritual Development',
  'Spiritual Growth',
  'Spiritual Healing',
  'Spiritual Psychology',
  'Spiritualism',
  'Spirituality',
  'Tantra',
  'Tarot',
  'The Secret',
  'Thelema',
  'Transformation',
  'Truth Seekers',
  'Vipassana Meditation',
  'Witchcraft',
  'Witches',
  'Zen Meditation',
];

export const family = [
  'Active Parents',
  'Adoption',
  'Adoptive Parents With Young Children',
  'African American Families',
  'Alternative Parenting',
  'Attachment Parenting',
  'Babies',
  'Babywearing',
  'Beziehung',
  'Bilingual Children',
  'Birthing Experience & Choices',
  'Breastfeeding',
  'Christian Parenting',
  'Cloth Diapers',
  'Clothing Swap',
  'Dads',
  'Divorced Parents',
  'Elternzeit',
  'Expecting Moms',
  'Expecting Parents',
  'Family',
  'Family Friendly',
  'First-Time Pregnant Moms',
  'Gay Parents',
  'Girl Scouts Parents',
  'Healthy Kids',
  'Healthy Moms',
  'Hip Mamas',
  'Homebirth',
  'Homeschooling',
  'Interracial Families',
  'Jewish Parenting',
  'Kids',
  'Military Moms',
  "Mom's Night Out",
  'Mommy and Me',
  'Moms',
  'Moms Support',
  'Moms of Todders',
  'Natural Birth',
  'Natural Parenting',
  'New Moms',
  'New Moms Support',
  'New Parents',
  'Older Parents',
  'Parents',
  'Parents of Teens',
  'Parents of Tweens',
  'Perinatal Fitness',
  'Playdates',
  'Pregnancy',
  'Pregnant Mom Support',
  'Preschoolers',
  'School-Age Kids',
  'Scouting',
  'Single Dads',
  'Single Moms',
  'Single Moms Support',
  'Single Parent Support',
  'Stay at Home Parents',
  'Stay-at-Home Dads',
  'Stay-at-Home Moms',
  'Stroller Fitness',
  'Stroller Workouts',
  'Support During First Pregnancy',
  'Toddlers',
  'Tweens',
  'Twins and Multiples',
  'Väter in Elternzeit',
  'Work at Home Moms',
  'Working Dads',
  'Working Moms',
  'Working Parents',
  'Young Moms',
];

export const videoGames = [
  'Apex Legends',
  'Among Us',
  'LAN Party',
  'Nintendo Switch',
  'Nintendo 64',
  'Online Gaming',
  'PC Gaming',
  'Pokemon',
  'Pokemon Go',
  'Playstation',
  'Playstation 4',
  'Playstation 5',
  'Retro game',
  'Role-Playing Game',
  'Super Famicom',
  'Super Mario',
  'Street Fighter',
  'Smash Bros',
  'Splatoon',
  'Tekken',
  'Wii',
  'War Game',
  'Warcraft & World of Warcraft',
  'Xbox',
];

export const petsAndAnimals = [
  'Active Dogs',
  'American Pit Bull Terrier',
  'Animal Rescue',
  'Animal Welfare',
  'Animals',
  'Beagle',
  'Birds',
  'Birdwatching',
  'Boston Terrier',
  'Boxer',
  'Chihuahua',
  'Corgi',
  'Dachshund',
  'Dog Agility',
  'Dog Parks',
  'Dog Playgroups',
  'Dog Rescue',
  'Dog Training',
  'Dog Walks',
  'Dogs',
  'English Bulldog',
  'French Bulldog',
  'German Shepherd',
  'Golden Retriever',
  'Great Dane',
  'Horses',
  'Italian Greyhound',
  'Labrador Retriever',
  'Large Breed Dogs',
  'Off-Leash Dog Recreation',
  'Pet Adoption',
  'Pet Chicken',
  'Pets',
  'Pug',
  'Puppies',
  'Samoyed',
  'Shiba Inu',
  'Siberian Husky',
  'Small Breed Dogs',
  'Small Dog Playgroup',
  'Toy Dogs',
  'Weimaraner',
  'Yorkshire Terrier',
];

export const photography = [
  'Adobe Lightroom',
  'Art Modeling',
  'Digital Photography',
  'Fashion Photography',
  'Food Photography',
  'Glamour Photography',
  'Group Photo Shoots',
  'Landscape Photography',
  'Location Photography',
  'Model Photography',
  'Modeling',
  'Models',
  'Nature Photography',
  'Photography',
  'Photography Classes',
  'Photojournalism',
  'Photoshop',
  'Portrait Photography',
  'Street Photography',
  'Studio Lighting',
  'Studio Photography',
  'Travel Photography',
  'Wedding Photography',
];

export const outdoors = [
  'Backpacking',
  'Beach',
  'biking',
  'Bicycling',
  'Boating',
  'Camping',
  'Canoeing',
  'Cross-Country Skiing',
  'Cruise',
  'Day Trip',
  'Dirt Biking',
  'Exploring',
  'Fishing',
  'Gardening',
  'Geocaching',
  'Hiking',
  'Horseback Riding',
  'Kayaking',
  'Longboarding',
  'Mountaineering',
  'Outdoors',
  'Paddling',
  'Park Games',
  'Picnic',
  'Rock Climbing',
  'Sailing',
  'Scuba Diving',
  'Sierra Club',
  'Sightseeing',
  'Skiing',
  'Snowboarding',
  'Snowshoeing',
  'Travel',
  'Survivalism',
  'Target Shooting',
  'Tours',
  'Trekking',
  'Urban Exploration',
  'Vacations',
  'Trips',
  'Whitewater Rafting',
];

export const sports = [
  'Aikido',
  'Airsoft',
  'Badminton',
  'Baseball',
  'Basketball',
  'Beach Volleyball',
  'Boston Bruins',
  'Boston Celtics',
  'Boston Red Sox',
  'Bowling',
  'Brazilian Jiu-Jitsu',
  'Capoeira',
  'Chicago Bears',
  'Chicago Blackhawks',
  'Chicago Bulls',
  'Chicago Cubs',
  'Chicago White Sox',
  'Circus Art',
  'Close Quarter Combat',
  'Co-Ed Adult Sports League',
  'Coed Recreational Sports',
  'Coed Soccer',
  'Cycling',
  'Disc Golf',
  'Diving',
  'Dodgeball',
  'Dragon Boating',
  'English Premier League',
  'Equestrian',
  'European Football',
  'Extreme Sports',
  'Fencing',
  'Firearms Training',
  'Flag Football',
  'Golf',
  'Gymnastics',
  'Hockey',
  'Hula Hooping',
  'Hunting',
  'Skating',
  'Jeet Kune Do',
  'Jiu Jitsu',
  'Kali',
  'Kickball',
  'Kung Fu',
  'Martial Arts',
  'NFL Football',
  'NHL Hockey',
  'New England Patriots',
  'New York Giants',
  'New York Jets',
  'New York Mets',
  'New York Yankees',
  'Paddle Boarding',
  'Paintball',
  'Philadelphia 76ers',
  'Philadelphia Eagles',
  'Philadelphia Flyers',
  'Philadelphia Phillies',
  'Ping Pong',
  'Racquetball',
  'Road Cycling',
  'Rugby',
  'Self-Defense',
  'Shooting Guns',
  'Skateboarding',
  'Soccer',
  'Softball',
  'Sports',
  'Surfing',
  'Table Tennis',
  'Tennis',
  'Frisbee',
  'Volleyball',
];

export const tech = [
  '.NET',
  '3D Animation',
  '3D Printing',
  'Agile',
  'Amazon Web Services',
  'Android',
  'Android Development',
  'AngularJS',
  'Arduino',
  'Artificial Intelligence',
  'Augmented Reality',
  'API',
  'Big Data',
  'Big Data Analytics',
  'Biotechnology',
  'Bitcoin',
  'Bitcoin Miners',
  'Blockchain',
  'Blogging',
  'Bots',
  'Business Analytics',
  'CMS (Content Management Systems)',
  'CSS3',
  'CUDA: Compute Unified Device Architecture',
  'Chatbots',
  'Clean Technology',
  'Cloud Computing',
  'Cloud Security',
  'ColdFusion',
  'Collaboration',
  'Computer Science',
  'Computer Security',
  'Computers',
  'Configuration Management',
  'Continuous Delivery',
  'Cryptocurrency',
  'Cryptography',
  'C sharp',
  'C plus plus',
  'Data Analytics',
  'Data Management',
  'Data Mining',
  'Data Science',
  'Data Visualization',
  'Database',
  'DevOps',
  'Docker',
  'Drupal',
  'Django',
  'Drone',
  'E-Commerce',
  'Electronics',
  'Extreme Programming',
  'Front-end Development',
  'Functional Programming',
  'Futurology',
  'GIS',
  'GPGPU',
  'GPU',
  'Game Design',
  'Game Programming',
  'Graphic Design',
  'HTML5',
  'Hacking',
  'HacksHackers',
  'Hadoop',
  'Haskell',
  'High Scalability Computing',
  'IaaS (Infrastructure as a Service)',
  'Independent Game Development',
  'Infrastructure as Code',
  'Internet of Things',
  'iOS',
  'iOS Development',
  'iPhone',
  'JIRA',
  'JQuery',
  'Java',
  'JavaScript',
  'JSfiddle',
  'Kanban',
  'Keras',
  'Kotlin',
  'LAMP',
  'Linux',
  'Matplotlib',
  'Machine Learning',
  'Metamask',
  'Mobile Development',
  'Mobile User Experience',
  'MongoDB',
  'MySQL',
  'Network Security',
  'NoSQL',
  'NodeJS',
  'Numpy',
  'Objective C',
  'Office 365',
  'Open Data',
  'Open Source',
  'OpenStack',
  'OpenAI',
  'OpenCV',
  'OpenGL',
  'Oracle',
  'PHP',
  'Pandas',
  'PaaS (Platform as a Service)',
  'Parallel Programming',
  'Podcasting',
  'PostgreSQL',
  'Product Design',
  'Product Development',
  'Python',
  'PyTorch',
  'Robotics',
  'Reactjs',
  'React Native',
  'Redux',
  'Ruby',
  'Ruby On Rails',
  'SEO',
  'SaaS (Software as a Service)',
  'Scala',
  'Scikit-learn',
  'SciPy',
  'Scrum',
  'Semantic Web',
  'Social Media',
  'Software Development',
  'Software Engineering',
  'Solidity',
  'Swift',
  'Svelte',
  'QA and Testing',
  'System Administration',
  'Theano',
  'Technology',
  'Test Automation',
  'Test Driven Development',
  'Tensorflow',
  'TypeScript',
  'UI Design',
  'UX Design',
  'Unity',
  'Usability',
  'User Experience',
  'User Research',
  'Ubuntu',
  'Video Game Design',
  'Virtual Reality',
  'Virtualization',
  'Vuejs',
  'Web3',
  'Web Design',
  'Web Development',
  'Web Security',
  'WordPress',
];

export const writings = [
  'Aspiring Writer',
  'Author',
  "Children's Fiction Writing",
  'Digital Publishing',
  'Fantasy Writing',
  'Fiction Writing',
  'Journalism',
  'Non-Fiction Writing',
  'Novel Writing',
  'Poetry Writing',
  'Science Fiction Writing',
  'Screenwriting',
  'Self-Publishing',
  'Short Stories',
  'Short Story Writing',
  "Writer's Block",
];
